# frozen_string_literal: true
# This import will load all other necessary scripts, e.g. capistrano/rvm or capistrano/bundler
# It will also import all capistrano rake tasks within the installed gems (lib/capistrano/tasks/*.rake)
require "capistrano/jelastic"

# Load DSL and Setup Up Stages
require "capistrano/setup"

# Includes default deployment tasks
require "capistrano/deploy"

# Include Jelastic deployment defaults
require "capistrano/jelastic"

# Includes tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#
# require 'capistrano/rvm'
# require 'capistrano/rbenv'
# require 'capistrano/chruby'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob("lib/capistrano/tasks/*.cap").each { |r| import r }
